(()=>{"use strict";const o="[data-today-in-history]";const s="ScienceHistory/science_today.json";const n="apcScienceHistorySnapshot:v2";const a=24;const i=t=>String(t==null?"":t).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");function c(t,e="",n=260){const o=typeof t==="string"?t.replace(/[\u0000-\u001f\u007f]+/g," ").replace(/\s+/g," ").trim():"";return(o||e).slice(0,n)}function r(){let t="/";try{if(window.KEEP&&window.KEEP.hexo_config&&window.KEEP.hexo_config.root){t=window.KEEP.hexo_config.root}else if(window.CONFIG&&window.CONFIG.root){t=window.CONFIG.root}}catch(t){}t=String(t||"/").trim();if(!t.startsWith("/")||t.startsWith("//")||t.includes("\\")||/(?:^|\/)\.\.(?:\/|$)/.test(t)||/%(?:2e|2f|5c)/i.test(t)||/[?#\u0000-\u001f\u007f]/.test(t))return"/";return t.endsWith("/")?t:`${t}/`}function l(t,e){const n=String(t||"").replace(/^\/+/,"");return`${e}${n}`.replace(/\/{2,}/g,"/")}function d(t){const e=String(t||"").trim();if(!e.startsWith("/")||e.startsWith("//")||e.includes("\\")||/(?:^|\/)\.\.(?:\/|$)/.test(e)||/[\u0000-\u001f\u007f]/.test(e))return"/2099/12/31/%E6%AF%8F%E6%97%A5%E6%96%B0%E9%97%BB/";return e}function u(t){if(typeof t==="string"){const o=c(t,"",320);if(!o)return null;const r=o.match(/^(\d{3,4}年?)\s*[：:—-]?\s*(.*)$/);return{label:r?r[1]:"",title:"",text:r&&r[2]?r[2]:o}}if(!t||typeof t!=="object")return null;const e=c(t.label||t.year,"",24);const n=c(t.title,"",100);const o=c(t.text||t.description,"",320);if(!e&&!n&&!o)return null;return{label:e,title:n,text:o}}function p(t,e){if(!t||typeof t!=="object"||!Array.isArray(t.items)){throw new Error("Invalid science-history snapshot")}const n=t.items.slice(0,a).map(u).filter(Boolean);if(!n.length)throw new Error("Science-history snapshot contains no verified items");const o=c(t.subtitle,[c(t.date_text,"",40),c(t.week,"",20)].filter(Boolean).join(" "),160);const r=c(t.date||t.generated_for||t.snapshot_date,"",32);const i=o.match(/\b\d{4}-\d{2}-\d{2}\b/);const s=/^\d{4}-\d{2}-\d{2}$/.test(r)?r:i?i[0]:"";return{version:Number.isFinite(Number(t.version))?Number(t.version):1,date:s,kicker:c(t.kicker,"SCIENCE HISTORY",60),title:c(t.title,"科技史上的今天",80),subtitle:o,items:n}}function f(){return`
      <div role="status" aria-live="polite" style="margin:16px 0;padding:18px 20px;border-radius:12px;background:rgba(127,127,127,.08);color:var(--font-color,#555);">
        正在加载今日科技史快照…
      </div>`}function g(){return`
      <div role="status" style="margin:16px 0;padding:18px 20px;border-left:4px solid #d97706;border-radius:10px;background:rgba(217,119,6,.1);color:var(--font-color,#555);line-height:1.7;">
        <strong>今日科技史快照暂时无法加载。</strong><br>
        定时任务会保留最近一次成功生成的文件；请稍后刷新页面。
      </div>`}function h(){let t="/2099/12/31/%E6%AF%8F%E6%97%A5%E6%96%B0%E9%97%BB/";try{const e=document.querySelector("#language-switch a");if(e&&typeof e.getAttribute==="function"){t=d(e.getAttribute("href"))}}catch(t){}return`
      <div role="status" style="margin:16px 0;padding:18px 20px;background:rgba(127,127,127,.08);border-radius:10px;line-height:1.65;color:var(--font-color,#555);">
        <p style="margin:0 0 10px;">Today's science-history data is currently available only in Chinese. The Chinese text is not embedded here because an editorially reviewed English edition is not yet available.</p>
        <a href="${i(t)}" lang="zh-CN" hreflang="zh-CN">Open the Chinese version of this article</a>
      </div>`}function y(t,e){const n=e?`<div role="status" style="margin:0 0 14px;padding:10px 12px;border-radius:8px;background:rgba(217,119,6,.1);color:var(--font-color,#555);">本站快照暂时不可用，正在展示浏览器中最近一次成功保存的内容。</div>`:"";const o=t.date?`本站每日快照 · ${i(t.date)}`:"本站每日快照";const r=t.items.map(t=>{const e=[t.label?`<span style="display:inline-block;margin-right:8px;color:#b45309;font-weight:700;">${i(t.label)}</span>`:"",t.title?`<strong>${i(t.title)}</strong>`:""].join("");return`
        <li style="padding:12px 0;border-bottom:1px solid rgba(127,127,127,.18);line-height:1.75;">
          ${e?`<div>${e}</div>`:""}
          ${t.text?`<div${e?' style="margin-top:3px;"':""}>${i(t.text)}</div>`:""}
        </li>`}).join("");return`
      ${n}
      <section style="max-width:900px;margin:16px auto;padding:20px;background:var(--card-bg,#fff);border-radius:12px;box-shadow:0 8px 24px rgba(149,157,165,.18);color:var(--font-color,#333);">
        <div style="font-size:12px;letter-spacing:.12em;color:#b45309;font-weight:700;">${i(t.kicker)}</div>
        <h2 style="margin:6px 0 0;font-size:24px;color:var(--font-color,#222);">${i(t.title)}</h2>
        ${t.subtitle?`<div style="margin-top:5px;color:var(--font-color,#666);opacity:.76;font-size:14px;">${i(t.subtitle)}</div>`:""}
        <ol style="list-style:none;padding:0;margin:12px 0 0;">${r}</ol>
        <div style="margin-top:12px;font-size:12px;opacity:.62;">${o}</div>
      </section>`}function x(t,e,n){const o=y(e,n);t.forEach(t=>{t.innerHTML=o})}function b(t){try{if(!window.localStorage)return null;const e=window.localStorage.getItem(n);return e?p(JSON.parse(e),t):null}catch(t){return null}}function m(t){try{if(window.localStorage)window.localStorage.setItem(n,JSON.stringify(t))}catch(t){}}async function v(e,n){try{const t=await fetch(l(s,n),{cache:"no-cache",credentials:"same-origin",headers:{Accept:"application/json"}});if(!t.ok)throw new Error(`Snapshot request failed (${t.status})`);const o=await t.text();const r=p(JSON.parse(o),n);m(r);x(e,r,false)}catch(t){const i=b(n);if(i){x(e,i,true)}else{e.forEach(t=>{t.innerHTML=g()})}try{console.error("[ScienceHistory] Local snapshot unavailable.",t)}catch(t){}}}function t(){const t=Array.from(document.querySelectorAll(o));if(!t.length)return;const e=String(document.documentElement&&document.documentElement.lang||"");if(/^en(?:-|$)/i.test(e)){const n=h();t.forEach(t=>{t.innerHTML=n});return}t.forEach(t=>{t.innerHTML=f()});v(t,r())}document.addEventListener("DOMContentLoaded",t)})();