(()=>{"use strict";const n="[data-today-in-history]";const s="ScienceHistory/science_today.json";const o="ScienceHistory/science_today.png";const r="apcScienceHistorySnapshot:v2";const a=24;const c=t=>String(t==null?"":t).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");function l(t,e="",r=260){const n=typeof t==="string"?t.replace(/[\u0000-\u001f\u007f]+/g," ").replace(/\s+/g," ").trim():"";return(n||e).slice(0,r)}function i(){let t="/";try{if(window.KEEP&&window.KEEP.hexo_config&&window.KEEP.hexo_config.root){t=window.KEEP.hexo_config.root}else if(window.CONFIG&&window.CONFIG.root){t=window.CONFIG.root}}catch(t){}t=String(t||"/").trim();if(!t.startsWith("/")||t.startsWith("//")||t.includes("\\")||/(?:^|\/)\.\.(?:\/|$)/.test(t)||/%(?:2e|2f|5c)/i.test(t)||/[?#\u0000-\u001f\u007f]/.test(t))return"/";return t.endsWith("/")?t:`${t}/`}function d(t,e){const r=String(t||"").replace(/^\/+/,"");return`${e}${r}`.replace(/\/{2,}/g,"/")}function u(t,e){let r=typeof t==="string"?t.trim():"";if(!r)return d(o,e);if(r.startsWith("//")||/^[a-z][a-z\d+.-]*:/i.test(r)||r.includes("\\")||/(?:^|\/)\.\.(?:\/|$)/.test(r)||/%(?:2e|2f|5c)/i.test(r)||/[?#\u0000-\u001f\u007f]/.test(r)||!/\.(?:png|jpe?g|webp|avif)$/i.test(r))return d(o,e);r=r.replace(/^\/+/,"");const n=e.replace(/^\/+|\/+$/g,"");if(n&&r.startsWith(`${n}/`))return`/${r}`;return d(r,e)}function p(t){const e=String(t||"").trim();if(!e.startsWith("/")||e.startsWith("//")||e.includes("\\")||/(?:^|\/)\.\.(?:\/|$)/.test(e)||/[\u0000-\u001f\u007f]/.test(e))return"/2099/12/31/%E6%AF%8F%E6%97%A5%E6%96%B0%E9%97%BB/";return e}function f(t){if(typeof t==="string"){const n=l(t,"",320);if(!n)return null;const o=n.match(/^(\d{3,4}年?)\s*[：:—-]?\s*(.*)$/);return{label:o?o[1]:"",title:"",text:o&&o[2]?o[2]:n}}if(!t||typeof t!=="object")return null;const e=l(t.label||t.year,"",24);const r=l(t.title,"",100);const n=l(t.text||t.description,"",320);if(!e&&!r&&!n)return null;return{label:e,title:r,text:n}}function g(t,e){if(!t||typeof t!=="object"||!Array.isArray(t.items)){throw new Error("Invalid science-history snapshot")}const r=t.items.slice(0,a).map(f).filter(Boolean);if(!r.length)throw new Error("Science-history snapshot contains no verified items");const n=l(t.subtitle,[l(t.date_text,"",40),l(t.week,"",20)].filter(Boolean).join(" "),160);const o=l(t.date||t.generated_for||t.snapshot_date,"",32);const i=n.match(/\b\d{4}-\d{2}-\d{2}\b/);const s=/^\d{4}-\d{2}-\d{2}$/.test(o)?o:i?i[0]:"";return{version:Number.isFinite(Number(t.version))?Number(t.version):1,date:s,kicker:l(t.kicker,"SCIENCE HISTORY",60),title:l(t.title,"科技史上的今天",80),subtitle:n,deck:l(t.deck,"",260),poster:u(t.poster||t.poster_url||t.image||t.image_url||t.local_url,e),items:r}}function h(){return`
      <div role="status" aria-live="polite" style="margin:16px 0;padding:18px 20px;border-radius:12px;background:rgba(127,127,127,.08);color:var(--font-color,#555);">
        正在加载今日科技史快照…
      </div>`}function y(){return`
      <div role="status" style="margin:16px 0;padding:18px 20px;border-left:4px solid #d97706;border-radius:10px;background:rgba(217,119,6,.1);color:var(--font-color,#555);line-height:1.7;">
        <strong>今日科技史快照暂时无法加载。</strong><br>
        定时任务会保留最近一次成功生成的文件；请稍后刷新页面。
      </div>`}function x(){let t="/2099/12/31/%E6%AF%8F%E6%97%A5%E6%96%B0%E9%97%BB/";try{const e=document.querySelector("#language-switch a");if(e&&typeof e.getAttribute==="function"){t=p(e.getAttribute("href"))}}catch(t){}return`
      <div role="status" style="margin:16px 0;padding:18px 20px;background:rgba(127,127,127,.08);border-radius:10px;line-height:1.65;color:var(--font-color,#555);">
        <p style="margin:0 0 10px;">Today's science-history data is currently available only in Chinese. The Chinese text and poster are not embedded here because an editorially reviewed English edition is not yet available.</p>
        <a href="${c(t)}" lang="zh-CN" hreflang="zh-CN">Open the Chinese version of this article</a>
      </div>`}function b(t,e){const r=e?`<div role="status" style="margin:0 0 14px;padding:10px 12px;border-radius:8px;background:rgba(217,119,6,.1);color:var(--font-color,#555);">本站快照暂时不可用，正在展示浏览器中最近一次成功保存的内容。</div>`:"";const n=t.date?`本站每日快照 · ${c(t.date)}`:"本站每日快照";const o=t.items.map(t=>{const e=[t.label?`<span style="display:inline-block;margin-right:8px;color:#b45309;font-weight:700;">${c(t.label)}</span>`:"",t.title?`<strong>${c(t.title)}</strong>`:""].join("");return`
        <li style="padding:12px 0;border-bottom:1px solid rgba(127,127,127,.18);line-height:1.75;">
          ${e?`<div>${e}</div>`:""}
          ${t.text?`<div${e?' style="margin-top:3px;"':""}>${c(t.text)}</div>`:""}
        </li>`}).join("");const i=t.date?`?v=${encodeURIComponent(t.date)}`:"";return`
      ${r}
      <section style="max-width:900px;margin:16px auto;padding:20px;background:var(--card-bg,#fff);border-radius:12px;box-shadow:0 8px 24px rgba(149,157,165,.18);color:var(--font-color,#333);">
        <div style="font-size:12px;letter-spacing:.12em;color:#b45309;font-weight:700;">${c(t.kicker)}</div>
        <h2 style="margin:6px 0 0;font-size:24px;color:var(--font-color,#222);">${c(t.title)}</h2>
        ${t.subtitle?`<div style="margin-top:5px;color:var(--font-color,#666);opacity:.76;font-size:14px;">${c(t.subtitle)}</div>`:""}
        ${t.deck?`<p style="margin:12px 0 4px;line-height:1.7;">${c(t.deck)}</p>`:""}
        <ol style="list-style:none;padding:0;margin:12px 0 0;">${o}</ol>
        <div style="margin-top:12px;font-size:12px;opacity:.62;">${n}</div>
      </section>
      <figure data-science-history-poster-wrap style="max-width:900px;margin:18px auto 0;">
        <img data-science-history-poster src="${c(t.poster+i)}" alt="${c(t.title)}长图" loading="lazy" decoding="async" style="display:block;width:100%;height:auto;border-radius:10px;box-shadow:0 6px 24px rgba(0,0,0,.08);">
      </figure>`}function m(t){if(!t||typeof t.querySelector!=="function")return;const e=t.querySelector("[data-science-history-poster]");if(!e||typeof e.addEventListener!=="function")return;e.addEventListener("error",()=>{const t=typeof e.closest==="function"?e.closest("[data-science-history-poster-wrap]"):null;if(t){t.innerHTML='<div role="status" style="padding:14px;border-radius:8px;background:rgba(127,127,127,.08);color:var(--font-color,#666);">今日长图快照暂时不可用，已保留上方经核验的文字记录。</div>'}},{once:true})}function v(t,e,r){const n=b(e,r);t.forEach(t=>{t.innerHTML=n;m(t)})}function w(t){try{if(!window.localStorage)return null;const e=window.localStorage.getItem(r);return e?g(JSON.parse(e),t):null}catch(t){return null}}function $(t){try{if(window.localStorage)window.localStorage.setItem(r,JSON.stringify(t))}catch(t){}}async function E(e,r){try{const t=await fetch(d(s,r),{cache:"no-cache",credentials:"same-origin",headers:{Accept:"application/json"}});if(!t.ok)throw new Error(`Snapshot request failed (${t.status})`);const n=await t.text();const o=g(JSON.parse(n),r);$(o);v(e,o,false)}catch(t){const i=w(r);if(i){v(e,i,true)}else{e.forEach(t=>{t.innerHTML=y()})}try{console.error("[ScienceHistory] Local snapshot unavailable.",t)}catch(t){}}}function t(){const t=Array.from(document.querySelectorAll(n));if(!t.length)return;const e=String(document.documentElement&&document.documentElement.lang||"");if(/^en(?:-|$)/i.test(e)){const r=x();t.forEach(t=>{t.innerHTML=r});return}t.forEach(t=>{t.innerHTML=h()});E(t,i())}document.addEventListener("DOMContentLoaded",t)})();