document.addEventListener("DOMContentLoaded",function(){const g=document.createElement("div");g.id="wiki-picture-container";g.className="m-auto max-w-4xl bg-white rounded-lg shadow-md p-5 my-6";const e=document.createElement("div");e.id="wiki-loading";e.className="flex justify-center items-center py-10";e.innerHTML=`
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
      <p class="ml-4 text-gray-600">正在加载维基百科每日图片...</p>
  `;g.appendChild(e);const t=document.getElementById("wiki-daily-placeholder");if(!t)return;t.parentNode.replaceChild(g,t);const n=new Date;const i=n.getFullYear();const s=String(n.getMonth()+1).padStart(2,"0");const c=String(n.getDate()).padStart(2,"0");const r=`${i}-${s}-${c}`;const d=`Template:POTD_protected/${r}`;fetch(`https://en.wikipedia.org/w/api.php?action=query&format=json&formatversion=2&prop=images&titles=${encodeURIComponent(d)}&origin=*`).then(e=>e.json()).then(e=>{if(!e.query||!e.query.pages||e.query.pages.length===0){throw new Error("未找到图片信息")}const t=e.query.pages[0];if(!t.images||t.images.length===0){throw new Error("未找到当日图片")}const a=t.images[0].title;return fetch(`https://en.wikipedia.org/w/api.php?action=query&format=json&prop=imageinfo&iiprop=url&titles=${encodeURIComponent(a)}&origin=*`).then(e=>e.json()).then(e=>{if(!e.query||!e.query.pages){throw new Error("未找到图片URL信息")}const t=Object.keys(e.query.pages)[0];const n=e.query.pages[t];if(!n.imageinfo||n.imageinfo.length===0){throw new Error("无法获取图片URL")}const r=n.imageinfo[0].url;const o=`https://api.allorigins.win/get?url=${encodeURIComponent(`https://en.wikipedia.org/w/index.php?title=${d}&action=raw`)}`;const l=document.createElement("img");l.src=r;l.alt=a.replace("File:","");l.className="w-full h-auto rounded-lg shadow-lg transition-transform duration-500 hover:scale-[1.02]";const p=document.createElement("div");p.className="text-xl font-bold text-gray-800 mb-4";p.textContent=`${i}年${s}月${c}日`;return fetch(o).then(e=>e.text()).then(e=>{try{const n=JSON.parse(e);const r=n.contents;const o=/^data:text\/x-wiki;\s*charset=UTF-8;base64,(.+)$/;const a=r.match(o);if(!a||!a[1]){const c=/^data:.*?;base64,(.+)$/;const d=r.match(c);if(!d||!d[1]){throw new Error("未找到有效的Base64数据")}console.warn("使用宽松匹配解析Base64数据");var t=d[1]}else{var t=a[1]}const i=atob(t);console.log(i);const s=extractDescription(i);renderContent(g,p,l,s)}catch(e){console.error("解码描述失败:",e);showImageWithError(g,p,l,"描述解码失败: "+e.message)}}).catch(e=>{console.error("获取描述失败:",e);showImageWithError(g,p,l,"无法获取描述信息: "+e.message)})}).catch(e=>{console.error("获取图片URL失败:",e);g.innerHTML=`
                      <div class="bg-red-50 border border-red-200 rounded-lg p-4">
                          <div class="flex items-center">
                              <i class="fas fa-exclamation-triangle text-red-500 mr-3"></i>
                              <p class="text-red-700">无法获取图片URL: ${e.message}</p>
                          </div>
                      </div>
                  `})}).catch(e=>{console.error("获取文件名失败:",e);g.innerHTML=`
              <div class="bg-red-50 border border-red-200 rounded-lg p-4">
                  <div class="flex items-center">
                      <i class="fas fa-exclamation-triangle text-red-500 mr-3"></i>
                      <p class="text-red-700">无法获取图片信息: ${e.message}</p>
                  </div>
              </div>
          `})});function renderContent(e,t,n,r){e.innerHTML="";const o=document.createElement("div");o.className="overflow-hidden rounded-lg shadow-lg mb-6";o.appendChild(n);e.appendChild(o);e.appendChild(t);if(r){const a=document.createElement("div");a.className="bg-gray-50 p-4 rounded-lg border border-gray-200";a.innerHTML=convertWikiToHtml(r);e.appendChild(a)}}function showImageWithError(e,t,n,r){e.innerHTML="";e.appendChild(t);const o=document.createElement("div");o.className="overflow-hidden rounded-lg shadow-lg mb-6";o.appendChild(n);e.appendChild(o);const a=document.createElement("div");a.className="bg-red-50 border border-red-200 rounded-lg p-4";a.innerHTML=`
      <div class="flex items-center">
          <i class="fas fa-exclamation-triangle text-red-500 mr-3"></i>
          <p class="text-red-700">${r}</p>
      </div>
  `;e.appendChild(a)}function extractDescription(n){const r='" |';const o=n.indexOf(r);if(o!==-1){const a=o+r.length;const i=['\n<div class="potd-recent"',"\n{{flatlist|class=potd-footer","\n|}<noinclude>","\n== See also =="];let e=-1;for(const s of i){const c=n.indexOf(s,a);if(c!==-1&&(e===-1||c<e)){e=c}}if(e===-1){e=n.length}let t=n.substring(a,e).trim();t=t.replace(/\n{2,}/g,"\n").replace(/^\s+|\s+$/g,"");return t||"无描述信息"}const e='<td class="description">';const t=n.indexOf(e);if(t!==-1){const a=t+e.length;const d="</td>";const l=n.indexOf(d,a);if(l!==-1){return n.substring(a,l).trim()}}return"无描述信息"}function convertWikiToHtml(e){if(!e)return"无描述信息";let t=e.replace(/'''(.+?)'''/g,"<strong>$1</strong>").replace(/''(.+?)''/g,"<em>$1</em>");t=t.replace(/\[\[([^\]|]+)\]\]/g,'<a href="https://en.wikipedia.org/wiki/$1">$1</a>');t=t.replace(/\[\[([^|]+)\|([^\]]+)\]\]/g,'<a href="https://en.wikipedia.org/wiki/$1">$2</a>');t=t.replace(/\[([^ ]+) ([^\]]+)\]/g,'<a href="$1">$2</a>');t=t.replace(/\n\n/g,"</p><p>");t=t.replace(/\n/g,"<br>");t=`<p>${t}</p>`;t=t.replace(/\{\{.*?\}\}/g,"");return t}